### PR TITLE
Implemented the possibility to access raw JSON of responses

### PR DESCRIPTION
**Pull request by emiliodallatorre**
This pull request adds the ability for users to access the raw JSON of API responses. This is particularly useful for those working on projects with custom REST APIs, where access to the underlying data format is crucial.

By adding this functionality, developers can easily work with custom APIs and extract the data they need. It also allows for greater flexibility in handling API responses and opens up new possibilities for custom integrations.

### CODE REVIEW

**Comment by ArunPrakashG** [comment]
Hey there! Thanks for checking out the package!
Now on to the topic, I think [Custom Requests](https://github.com/ArunPrakashG/wordpress_client/wiki/Custom-Requests) covers this topic and offers complete control over the request.
Could you please check that out and let me know?

**Comment by emiliodallatorre** [comment]
Hi, in fact this is not 100% true: custom requests enable you to create new kind of requests... accessing raw json permits you to access other properties of existing classes, like Yoast! SEO metadata added to posts, without implementing a totally new kind of response...!

**Review by ArunPrakashG — APPROVED** [review]

**Comment by ArunPrakashG** [comment]
I understand, Thanks for the contribution. I will merge this PR. However, i have few changes planned for the library and would like to release this to pub.dev with those included.
Meanwhile, you could use this repo directly by specifying the Git URL on pubspec.yaml file.
If you need further help in this regard, let me know!

**Comment by emiliodallatorre** [comment]
Thank you!

**Pull request merged**
